services:
  postgres:
    image: postgres:16
    container_name: tfg-db
    environment:
      POSTGRES_PASSWORD: tfg1234
      POSTGRES_DB: tfg_db
    ports:
      - "5432:5432"
    volumes:
      - tfg_volumen:/var/lib/postgresql/data

volumes:
  tfg_volumen: